### ISSUE TITLE
Opening share takes forever the first time until "Send failed", afterwards instantaneous

### ISSUE THREAD

**Issue by courville** [AgNO3/jcifs-ng#268]
In my Android application right after opening the application, opening an SMB2 only synology server takes a long time without log activity until getting `Send failed`. Afterwards reopening the server share gets the result instantaneously.
I captured the attached TRACE logs with `jcifs.netbios.NameServiceClientImpl`, `jcifs.smb.SmbSessionImpl` and `jcifs.smb.SmbTransportImpl`.

Following config is used this time (I try to get away from the SMB1/2 active probing):
```
prop.put("jcifs.smb.client.enableSMB2", true);
prop.put("jcifs.smb.client.useSMB2Negotiation", "false");
prop.put("jcifs.smb.client.disableSMB1", "false");
prop.put("jcifs.smb.client.ipcSigningEnforced", "false");
prop.put("jcifs.smb.client.disablePlainTextPasswords", "false");
prop.put("jcifs.smb.client.dfs.disabled", "true");
prop.put("jcifs.smb.useRawNTLM", "true");
```

Logs: [org.courville.nova-smbTimeoutDS720p-then-instantaneous-then-download.zip](https://github.com/AgNO3/jcifs-ng/files/5869307/org.courville.nova-smbTimeoutDS720p-then-instantaneous-then-download.zip)

**Comment by courville** [comment]
I do not know if it helps but surprisingly, when using `jcifs.resolveOrder="BCAST,DNS"`, this behavior that is systematic, is not reproductible anymore (at least that easy).

**Comment by mbechler** [comment]
It appears that the thread establishing the connection is interrupted. Not really sure why this would be the case. Could there be any reason the thread could be interrupted by external code?
Logging on jcifs.util.transport.Transport could reveal some more details as well.

**Comment by courville** [comment]
OK sadly enough I cannot reproduce for now with Transport logs. Will try harder and get back to you.

**Comment by courville** [comment]
OK for some reasons I have it again with frequency of one out of three.
Here are the logs requested including `jcifs.util.transport.Transport`: 
[org.courville.nova-sendFailed.zip](https://github.com/AgNO3/jcifs-ng/files/6095131/org.courville.nova-sendFailed.zip)
Please do not hesitate to ask for more if needed.
Thanks for your support.

**Comment by mbechler** [comment]
Does not look like the interrupt is coming from Transport, so I do not think it is triggered by jcifs. Could be external code or maybe even the platform (AsyncTask canceled?). 
jcifs however probably should disconnect the transport in this situation, as otherwise it is left in a broken state, ultimately leading to timeout on the next request, which I think is the delay you are experiencing.

**Comment by courville** [comment]
Thanks for the feedback. I will check on my end if it is triggered by my code. Do you plan to tackle the resulting broken state on your end?

**Comment by mbechler** [comment]
Digging a bit further into that, disconnecting the transport may not be necessary (not quite sure whether it would still be better to do that at this point). But, I found a bug skipping unexpected (response to the interrupted/cancelled request) messages when using SMB2. This should be fixed in master, please check whether this fixes the issue.

**Comment by courville** [comment]
Just integrated master in nova (my app), and gave it some test. So far so good \o/. I will deploy with beta users and check feedback. Thanks for following it through, this is somehow the last annoying behavior that I found with the install base.

**Comment by courville** [comment]
Let's declare this issue closed. Will reopen if need be. Thank you a lot for the continuous dedicated support.
