### ISSUE TITLE
 Does jcifs-ng-2.1.10 support jdk21?

### ISSUE THREAD

**Issue by kaiyang23** [AgNO3/jcifs-ng#360]
Does jcifs-ng-2.1.10 support jdk21?

**Comment by mbechler** [comment]
I don't believe there should be anything major preventing use with jdk21. Have you tried?

**Comment by kaiyang23** [comment]
I tried, it has error when I use jdk21 to compile source code,
The compile command is: mvn clean package -file pom.xml -Dmaven.wagon.http.ssl.insecure=true
![image](https://github.com/user-attachments/assets/3627d690-099d-4bc2-877c-8ba63288776f)

**Comment by mbechler** [comment]
This is due to the new JDK no longer supporting backward compatibility levels down to 7 (which the official jcifs-ng binaries still support). If you want to build jcifs-ng yourself and use JDK 21 for that, I you just be able to raise _java.sourceVersion_ and _java.targetVersion_ in _pom.xml_ to 1.8.

**Comment by kaiyang23** [comment]
It works , thanks for your help!
